---
services:
  # web:
  #   image: httpd
  #   ports:
  #     - "80:80"
  #   links:
  #     - fluentd
  #   logging:
  #     driver: "fluentd"
  #     options:
  #       fluentd-address: localhost:24224
  #       tag: httpd.access

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    networks:
      - elkstack

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    mem_limit: 1g
    depends_on:
      - elasticsearch
    networks:
      - elkstack

  fluent-bit:
    image: fluent/fluent-bit:3.1.4
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/conf:/fluent-bit/etc
      - ./logs:/logs
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elkstack
    depends_on:
      - elasticsearch

networks:
  elkstack:
    driver: bridge
